import { Business, Workflow, Call } from '@/types'

export const SEED_BUSINESSES: Business[] = [
  {
    id: 'biz_bakery',
    owner_id: 'demo-user-1',
    name: 'Sweet Delights Bakery',
    type: 'cake_shop',
    phone: '+91 98765 43210',
    description: 'Boutique custom cake shop specializing in designer birthday and wedding cakes.',
    language: 'en',
    created_at: new Date(Date.now() - 86400000 * 7).toISOString(),
    updated_at: new Date(Date.now() - 86400000 * 7).toISOString(),
  },
  {
    id: 'biz_clinic',
    owner_id: 'demo-user-1',
    name: 'Apex Family Clinic',
    type: 'clinic',
    phone: '+91 98765 11111',
    description: 'Multi-speciality outpatient healthcare center offering general consultations and specialist visits.',
    language: 'en',
    created_at: new Date(Date.now() - 86400000 * 6).toISOString(),
    updated_at: new Date(Date.now() - 86400000 * 6).toISOString(),
  },
  {
    id: 'biz_delivery',
    owner_id: 'demo-user-1',
    name: 'FastTrack Logistics',
    type: 'delivery',
    phone: '+91 99887 76655',
    description: 'Express citywide courier, package delivery, and parcel logistics service.',
    language: 'en',
    created_at: new Date(Date.now() - 86400000 * 5).toISOString(),
    updated_at: new Date(Date.now() - 86400000 * 5).toISOString(),
  },
  {
    id: 'biz_realestate',
    owner_id: 'demo-user-1',
    name: 'Prime Properties',
    type: 'real_estate',
    phone: '+91 88776 65544',
    description: 'Real estate advisory helping buyers and tenants find apartments, villas, and commercial spaces.',
    language: 'en',
    created_at: new Date(Date.now() - 86400000 * 4).toISOString(),
    updated_at: new Date(Date.now() - 86400000 * 4).toISOString(),
  },
  {
    id: 'biz_repair',
    owner_id: 'demo-user-1',
    name: 'QuickFix Home Services',
    type: 'repair',
    phone: '+91 77665 54433',
    description: 'On-demand plumbing, electrical, and appliance home repair technicians.',
    language: 'en',
    created_at: new Date(Date.now() - 86400000 * 3).toISOString(),
    updated_at: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
]

export const SEED_WORKFLOWS: Workflow[] = [
  {
    id: 'wf_cake_intake',
    business_id: 'biz_bakery',
    name: 'Cake Order & Enquiry Intake',
    trigger: 'missed_call',
    greeting: "Hi! Thanks for calling Sweet Delights Bakery. Sorry we missed your call. I'm your Voice AI assistant. Are you calling to place a cake order or do you have a general enquiry?",
    closing_message: "Thank you! We've received your order details and our bakery chef will confirm shortly. Have a wonderful day!",
    language: 'en',
    fields: [
      { id: 'f1', label: 'Order Type', key: 'order_type', type: 'select', required: true, options: ['Custom Cake', 'Birthday Cake', 'Wedding Cake', 'General Enquiry'], order: 1 },
      { id: 'f2', label: 'Cake Flavour', key: 'flavour', type: 'text', required: true, order: 2 },
      { id: 'f3', label: 'Weight (kg)', key: 'weight', type: 'number', required: false, order: 3 },
      { id: 'f4', label: 'Required Date', key: 'required_date', type: 'date', required: true, order: 4 },
      { id: 'f5', label: 'Custom Message', key: 'custom_message', type: 'text', required: false, order: 5 },
      { id: 'f6', label: 'Delivery or Pickup', key: 'delivery_preference', type: 'select', required: true, options: ['Delivery', 'Pickup'], order: 6 },
      { id: 'f7', label: 'Budget', key: 'budget', type: 'text', required: false, order: 7 },
      { id: 'f8', label: 'Caller Name', key: 'caller_name', type: 'text', required: true, order: 8 },
    ],
    conditions: [
      { id: 'c1', field: 'required_date', operator: 'less_than', value: '24', action: 'mark_urgent', action_label: 'If required within 24 hours → mark as urgent' },
    ],
    post_action: 'create_record',
    calendar_enabled: true,
    is_active: true,
    created_at: new Date(Date.now() - 86400000 * 7).toISOString(),
    updated_at: new Date(Date.now() - 86400000 * 7).toISOString(),
  },
  {
    id: 'wf_clinic_appt',
    business_id: 'biz_clinic',
    name: 'Doctor Appointment Booking',
    trigger: 'missed_call',
    greeting: "Hello! You've reached Apex Family Clinic. Sorry we missed your call. I'm your virtual assistant. Are you calling to book a new appointment, reschedule, cancel, or do you have an enquiry?",
    closing_message: "Thank you! Your appointment request has been scheduled on our calendar. We'll send a confirmation SMS shortly.",
    language: 'en',
    fields: [
      { id: 'f1', label: 'Request Type', key: 'request_type', type: 'select', required: true, options: ['New Appointment', 'Reschedule', 'Cancel', 'General Enquiry'], order: 1 },
      { id: 'f2', label: 'Patient Name', key: 'patient_name', type: 'text', required: true, order: 2 },
      { id: 'f3', label: 'Preferred Doctor / Speciality', key: 'doctor_preference', type: 'text', required: false, order: 3 },
      { id: 'f4', label: 'Preferred Date', key: 'preferred_date', type: 'date', required: true, order: 4 },
      { id: 'f5', label: 'Preferred Time', key: 'preferred_time', type: 'time', required: false, order: 5 },
      { id: 'f6', label: 'Reason for Visit', key: 'reason', type: 'text', required: false, order: 6 },
      { id: 'f7', label: 'Contact Number', key: 'contact_number', type: 'text', required: true, order: 7 },
    ],
    conditions: [
      { id: 'c1', field: 'request_type', operator: 'equals', value: 'New Appointment', action: 'create_calendar_event', action_label: 'If new appointment → create Google Calendar event' },
    ],
    post_action: 'create_calendar_event',
    calendar_enabled: true,
    is_active: true,
    created_at: new Date(Date.now() - 86400000 * 6).toISOString(),
    updated_at: new Date(Date.now() - 86400000 * 6).toISOString(),
  },
  {
    id: 'wf_delivery_dispatch',
    business_id: 'biz_delivery',
    name: 'Delivery Request & Status Handler',
    trigger: 'missed_call',
    greeting: "Hi! This is FastTrack Logistics. Sorry we missed your call. Are you calling to book a new delivery, track an existing order, or need help with a delivery?",
    closing_message: "Thank you! Your delivery request or tracking inquiry has been recorded. Our team is on it!",
    language: 'en',
    fields: [
      { id: 'f1', label: 'Request Type', key: 'request_type', type: 'select', required: true, options: ['New Delivery', 'Track Existing', 'Support'], order: 1 },
      { id: 'f2', label: 'Tracking / Order ID', key: 'tracking_number', type: 'text', required: false, order: 2 },
      { id: 'f3', label: 'Pickup Location', key: 'pickup_location', type: 'text', required: false, order: 3 },
      { id: 'f4', label: 'Delivery Location', key: 'delivery_location', type: 'text', required: false, order: 4 },
      { id: 'f5', label: 'Package Type', key: 'package_type', type: 'text', required: false, order: 5 },
      { id: 'f6', label: 'Contact Number', key: 'contact_number', type: 'text', required: true, order: 6 },
    ],
    conditions: [
      { id: 'c1', field: 'request_type', operator: 'equals', value: 'Track Existing', action: 'create_callback', action_label: 'Look up live courier status via API' },
    ],
    post_action: 'create_record',
    calendar_enabled: false,
    is_active: true,
    created_at: new Date(Date.now() - 86400000 * 5).toISOString(),
    updated_at: new Date(Date.now() - 86400000 * 5).toISOString(),
  },
  {
    id: 'wf_realestate_lead',
    business_id: 'biz_realestate',
    name: 'Property Lead & Site Visit Booking',
    trigger: 'missed_call',
    greeting: "Hello! Thanks for calling Prime Properties. Sorry we missed you. I'm your AI assistant. Are you looking to buy, rent, sell a property, or schedule a site visit?",
    closing_message: "Thank you! We've noted your property preferences. A consultant will reach out with curated options.",
    language: 'en',
    fields: [
      { id: 'f1', label: 'Interest Type', key: 'interest_type', type: 'select', required: true, options: ['Buy', 'Rent', 'Sell', 'Site Visit'], order: 1 },
      { id: 'f2', label: 'Property Type', key: 'property_type', type: 'select', required: true, options: ['Apartment', 'Villa', 'Commercial', 'Plot'], order: 2 },
      { id: 'f3', label: 'Preferred Location', key: 'location', type: 'text', required: true, order: 3 },
      { id: 'f4', label: 'Budget Range', key: 'budget', type: 'text', required: true, order: 4 },
      { id: 'f5', label: 'Visit Date', key: 'visit_date', type: 'date', required: false, order: 5 },
      { id: 'f6', label: 'Contact Name', key: 'contact_name', type: 'text', required: true, order: 6 },
    ],
    conditions: [
      { id: 'c1', field: 'interest_type', operator: 'equals', value: 'Site Visit', action: 'create_calendar_event', action_label: 'If site visit → schedule appointment on Google Calendar' },
    ],
    post_action: 'create_calendar_event',
    calendar_enabled: true,
    is_active: true,
    created_at: new Date(Date.now() - 86400000 * 4).toISOString(),
    updated_at: new Date(Date.now() - 86400000 * 4).toISOString(),
  },
  {
    id: 'wf_repair_service',
    business_id: 'biz_repair',
    name: 'Emergency Repair & Service Request',
    trigger: 'missed_call',
    greeting: "Hello! You've reached QuickFix Home Services. Sorry we missed your call. What repair or maintenance service do you need help with today?",
    closing_message: "Your service request has been registered. For emergencies, our nearest technician is being dispatched.",
    language: 'en',
    fields: [
      { id: 'f1', label: 'Service Type', key: 'service_type', type: 'text', required: true, order: 1 },
      { id: 'f2', label: 'Issue Description', key: 'issue_description', type: 'text', required: true, order: 2 },
      { id: 'f3', label: 'Service Address', key: 'address', type: 'text', required: true, order: 3 },
      { id: 'f4', label: 'Urgency Level', key: 'urgency', type: 'select', required: true, options: ['Normal', 'Urgent', 'Emergency'], order: 4 },
      { id: 'f5', label: 'Preferred Time Slot', key: 'preferred_time', type: 'text', required: false, order: 5 },
      { id: 'f6', label: 'Contact Number', key: 'contact_number', type: 'text', required: true, order: 6 },
    ],
    conditions: [
      { id: 'c1', field: 'urgency', operator: 'equals', value: 'Emergency', action: 'mark_urgent', action_label: 'If emergency → mark as high priority urgent callback' },
    ],
    post_action: 'create_record',
    calendar_enabled: true,
    is_active: true,
    created_at: new Date(Date.now() - 86400000 * 3).toISOString(),
    updated_at: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
]

export const SEED_CALLS: Call[] = [
  {
    id: 'call_001',
    business_id: 'biz_bakery',
    workflow_id: 'wf_cake_intake',
    caller_name: 'Priya Sharma',
    caller_phone: '+91 98111 22334',
    status: 'completed',
    intent: 'Custom Birthday Cake',
    summary: 'Caller requested a 1.5kg Belgian Chocolate Truffle cake for tomorrow afternoon. Marked urgent due to <24h deadline requirement.',
    urgency: 'urgent',
    follow_up_status: 'pending',
    transcript: [
      { role: 'assistant', content: "Hi! Thanks for calling Sweet Delights Bakery. Sorry we missed your call. I'm your Voice AI assistant. Are you calling to place a cake order or do you have a general enquiry?", timestamp: new Date(Date.now() - 3600000 * 2).toISOString() },
      { role: 'user', content: 'Hi, I need a 1.5kg Belgian chocolate truffle cake urgently for tomorrow afternoon.', timestamp: new Date(Date.now() - 3600000 * 2 + 15000).toISOString() },
      { role: 'assistant', content: 'I have recorded your order for a 1.5kg Belgian Chocolate Truffle cake for tomorrow afternoon. Would you prefer home delivery or pickup?', timestamp: new Date(Date.now() - 3600000 * 2 + 30000).toISOString() },
      { role: 'user', content: 'Delivery to Indiranagar please. My name is Priya Sharma.', timestamp: new Date(Date.now() - 3600000 * 2 + 45000).toISOString() },
      { role: 'assistant', content: "Thank you, Priya! We've received your order details and our bakery chef will confirm shortly. Have a wonderful day!", timestamp: new Date(Date.now() - 3600000 * 2 + 60000).toISOString() },
    ],
    collected_data: {
      order_type: 'Custom Birthday Cake',
      flavour: 'Belgian Chocolate Truffle',
      weight: '1.5',
      required_date: 'Tomorrow afternoon (<24h)',
      delivery_preference: 'Delivery',
      caller_name: 'Priya Sharma',
      address: 'Indiranagar',
    },
    language_used: 'en',
    duration_seconds: 75,
    calendar_event_id: 'sim_cake_001',
    calendar_event_url: 'https://calendar.google.com',
    created_at: new Date(Date.now() - 3600000 * 2).toISOString(),
    updated_at: new Date(Date.now() - 3600000 * 2).toISOString(),
  },
  {
    id: 'call_002',
    business_id: 'biz_clinic',
    workflow_id: 'wf_clinic_appt',
    caller_name: 'Rahul Mehta',
    caller_phone: '+91 98222 33445',
    status: 'completed',
    intent: 'Doctor Appointment',
    summary: 'Patient scheduled an in-person consultation with Dr. Sharma for tomorrow at 4:00 PM. Verified calendar slot availability and booked calendar event.',
    urgency: 'normal',
    follow_up_status: 'contacted',
    transcript: [
      { role: 'assistant', content: "Hello! You've reached Apex Family Clinic. Sorry we missed your call. I'm your virtual assistant. Are you calling to book a new appointment, reschedule, cancel, or do you have an enquiry?", timestamp: new Date(Date.now() - 3600000 * 5).toISOString() },
      { role: 'user', content: 'I want to book an appointment with Dr. Sharma tomorrow at 4 PM.', timestamp: new Date(Date.now() - 3600000 * 5 + 15000).toISOString() },
      { role: 'assistant', content: 'I checked our calendar and 4:00 PM tomorrow with Dr. Sharma is available! May I have your full name to confirm the booking?', timestamp: new Date(Date.now() - 3600000 * 5 + 30000).toISOString() },
      { role: 'user', content: 'My name is Rahul Mehta, phone number is 9822233445.', timestamp: new Date(Date.now() - 3600000 * 5 + 45000).toISOString() },
      { role: 'assistant', content: 'Appointment confirmed for Rahul Mehta with Dr. Sharma on tomorrow at 4:00 PM. Event created in Google Calendar. See you then!', timestamp: new Date(Date.now() - 3600000 * 5 + 60000).toISOString() },
    ],
    collected_data: {
      request_type: 'New Appointment',
      patient_name: 'Rahul Mehta',
      doctor_preference: 'Dr. Sharma',
      preferred_date: 'Tomorrow',
      preferred_time: '16:00',
      contact_number: '+91 98222 33445',
    },
    language_used: 'en',
    duration_seconds: 90,
    calendar_event_id: 'gcal_ev_apex_901',
    calendar_event_url: 'https://calendar.google.com/calendar/event?eid=apex901',
    created_at: new Date(Date.now() - 3600000 * 5).toISOString(),
    updated_at: new Date(Date.now() - 3600000 * 5).toISOString(),
  },
  {
    id: 'call_003',
    business_id: 'biz_delivery',
    workflow_id: 'wf_delivery_dispatch',
    caller_name: 'Anjali Patel',
    caller_phone: '+91 98333 44556',
    status: 'completed',
    intent: 'Delivery Status Lookup',
    summary: 'Caller inquired about tracking number ORD-101. External Delivery API tool returned: Out for Delivery in Indiranagar, arriving by 4:30 PM.',
    urgency: 'normal',
    follow_up_status: 'resolved',
    transcript: [
      { role: 'assistant', content: "Hi! This is FastTrack Logistics. Sorry we missed your call. Are you calling to book a new delivery, track an existing order, or need help with a delivery?", timestamp: new Date(Date.now() - 3600000 * 8).toISOString() },
      { role: 'user', content: 'Can you please check the status of my order with tracking number ORD-101?', timestamp: new Date(Date.now() - 3600000 * 8 + 12000).toISOString() },
      { role: 'assistant', content: 'Order ORD-101 is currently Out for Delivery! Current location: Indiranagar 100ft Road, Bangalore. Expected delivery is today by 4:30 PM.', timestamp: new Date(Date.now() - 3600000 * 8 + 24000).toISOString() },
      { role: 'user', content: 'Perfect, thank you so much!', timestamp: new Date(Date.now() - 3600000 * 8 + 36000).toISOString() },
      { role: 'assistant', content: "You're welcome, Anjali! Thank you for choosing FastTrack Logistics.", timestamp: new Date(Date.now() - 3600000 * 8 + 48000).toISOString() },
    ],
    collected_data: {
      request_type: 'Track Existing',
      tracking_number: 'ORD-101',
      status: 'Out for Delivery',
      eta: 'Today by 4:30 PM',
      location: 'Indiranagar 100ft Road',
      caller_name: 'Anjali Patel',
    },
    language_used: 'en',
    duration_seconds: 52,
    created_at: new Date(Date.now() - 3600000 * 8).toISOString(),
    updated_at: new Date(Date.now() - 3600000 * 8).toISOString(),
  },
  {
    id: 'call_004',
    business_id: 'biz_repair',
    workflow_id: 'wf_repair_service',
    caller_name: 'Vikram Singh',
    caller_phone: '+91 98444 55667',
    status: 'completed',
    intent: 'Emergency Pipe Repair',
    summary: 'Urgent emergency: Burst bathroom pipe with water flooding. Flagged for immediate priority dispatch.',
    urgency: 'urgent',
    follow_up_status: 'contacted',
    transcript: [
      { role: 'assistant', content: "Hello! You've reached QuickFix Home Services. Sorry we missed your call. What repair or maintenance service do you need help with today?", timestamp: new Date(Date.now() - 3600000 * 12).toISOString() },
      { role: 'user', content: 'Emergency! Pipe burst in bathroom, need a repair technician immediately!', timestamp: new Date(Date.now() - 3600000 * 12 + 15000).toISOString() },
      { role: 'assistant', content: "I've flagged this as an EMERGENCY. What is your address and contact name?", timestamp: new Date(Date.now() - 3600000 * 12 + 30000).toISOString() },
      { role: 'user', content: 'Flat 402, Green Glen Layout, Bellandur. Vikram Singh, 9844455667.', timestamp: new Date(Date.now() - 3600000 * 12 + 45000).toISOString() },
      { role: 'assistant', content: 'Emergency service request registered for Bellandur. Our emergency on-call plumber has been dispatched!', timestamp: new Date(Date.now() - 3600000 * 12 + 60000).toISOString() },
    ],
    collected_data: {
      service_type: 'Plumbing',
      issue_description: 'Burst bathroom pipe flooding',
      urgency: 'Emergency',
      address: 'Flat 402, Green Glen Layout, Bellandur',
      caller_name: 'Vikram Singh',
      contact_number: '+91 98444 55667',
    },
    language_used: 'en',
    duration_seconds: 64,
    created_at: new Date(Date.now() - 3600000 * 12).toISOString(),
    updated_at: new Date(Date.now() - 3600000 * 12).toISOString(),
  },
  {
    id: 'call_005',
    business_id: 'biz_bakery',
    workflow_id: 'wf_cake_intake',
    caller_name: 'सुरेश कुमार (Suresh Kumar)',
    caller_phone: '+91 98555 66778',
    status: 'completed',
    intent: 'केक ऑर्डर (Hindi Cake Order)',
    summary: 'ग्राहक ने कल शाम तक 2 किलो चॉकलेट केक की होम डिलीवरी का अनुरोध किया। हिंदी में बात की गई।',
    urgency: 'urgent',
    follow_up_status: 'pending',
    transcript: [
      { role: 'assistant', content: "नमस्ते! Sweet Delights Bakery में आपका स्वागत है। क्या आप केक ऑर्डर करना चाहते हैं या कोई सामान्य जानकारी चाहिए?", timestamp: new Date(Date.now() - 3600000 * 16).toISOString() },
      { role: 'user', content: 'मुझे कल शाम तक 2 किलो चॉकलेट केक चाहिए, घर पर डिलीवरी करें।', timestamp: new Date(Date.now() - 3600000 * 16 + 18000).toISOString() },
      { role: 'assistant', content: 'जी बिल्कुल! 2 किलो चॉकलेट केक कल शाम की डिलीवरी के लिए नोट कर लिया गया है। कृपया अपना नाम और डिलीवरी पता बताएं।', timestamp: new Date(Date.now() - 3600000 * 16 + 36000).toISOString() },
      { role: 'user', content: 'मेरा नाम सुरेश कुमार है, एमजी रोड, बैंगलोर।', timestamp: new Date(Date.now() - 3600000 * 16 + 54000).toISOString() },
      { role: 'assistant', content: 'धन्यवाद सुरेश जी! आपका 2 किलो चॉकलेट केक ऑर्डर बुक हो चुका है। हमारी टीम जल्द ही आपसे संपर्क करेगी।', timestamp: new Date(Date.now() - 3600000 * 16 + 72000).toISOString() },
    ],
    collected_data: {
      order_type: 'चॉकलेट केक (Chocolate Cake)',
      flavour: 'Chocolate',
      weight: '2',
      required_date: 'कल शाम (Tomorrow evening)',
      delivery_preference: 'Delivery',
      caller_name: 'सुरेश कुमार (Suresh Kumar)',
      address: 'MG Road, Bangalore',
    },
    language_used: 'hi',
    duration_seconds: 82,
    created_at: new Date(Date.now() - 3600000 * 16).toISOString(),
    updated_at: new Date(Date.now() - 3600000 * 16).toISOString(),
  },
]
